[package]
name = "my-macros"
version = "0.1.0"
authors = ["Todd Greenwood <pub+github@zwrob.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
